# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptiveEMA <- function(prices, alphas) {
    .Call('_techchart_adaptiveEMA', PACKAGE = 'techchart', prices, alphas)
}

bias_cpp <- function(data, orderside_long, max_mins_wait) {
    .Call('_techchart_bias_cpp', PACKAGE = 'techchart', data, orderside_long, max_mins_wait)
}

cpt_trend <- function(x, y, Q, minseglen, penalty) {
    .Call('_techchart_cpt_trend', PACKAGE = 'techchart', x, y, Q, minseglen, penalty)
}

houghtransform <- function(x1, y1, flag, rbucket, abucket, s) {
    .Call('_techchart_houghtransform', PACKAGE = 'techchart', x1, y1, flag, rbucket, abucket, s)
}

ma <- function(x, k, weighting) {
    .Call('_techchart_ma', PACKAGE = 'techchart', x, k, weighting)
}

timesTwo <- function(x) {
    .Call('_techchart_timesTwo', PACKAGE = 'techchart', x)
}

findminima <- function(xmin, xmax, threshold) {
    .Call('_techchart_findminima', PACKAGE = 'techchart', xmin, xmax, threshold)
}

findminima_pt <- function(xmin, xmax, threshold) {
    .Call('_techchart_findminima_pt', PACKAGE = 'techchart', xmin, xmax, threshold)
}

findmaxima <- function(xmin, xmax, threshold) {
    .Call('_techchart_findmaxima', PACKAGE = 'techchart', xmin, xmax, threshold)
}

findmaxima_pt <- function(xmin, xmax, threshold) {
    .Call('_techchart_findmaxima_pt', PACKAGE = 'techchart', xmin, xmax, threshold)
}

sortoptimaposition <- function(pos, sign, value) {
    .Call('_techchart_sortoptimaposition', PACKAGE = 'techchart', pos, sign, value)
}

sortoptimasign <- function(pos, sign, value) {
    .Call('_techchart_sortoptimasign', PACKAGE = 'techchart', pos, sign, value)
}

checkoptimasign <- function(sign) {
    .Call('_techchart_checkoptimasign', PACKAGE = 'techchart', sign)
}

checkoptimapos <- function(pos) {
    .Call('_techchart_checkoptimapos', PACKAGE = 'techchart', pos)
}

